### ISSUE TITLE
Niespójność w logice opcji "Back to Baking"

### ISSUE THREAD

**Issue by xiega** [NAME4YOU/Cookie-Simulator---PP#1]
### **Tytuł:** Niespójność w logice opcji "Back to Baking"
---
**Opis:**  
Opcja **"Back to Baking"** w menu wyświetla komunikat **"Returning to baking…"**, jednak w kodzie zastosowano komendę `break`. Powoduje to, że aplikacja nie wraca do procesu wypiekania ciasteczek, co skutkuje brakiem oczekiwanego działania i dezorientacją użytkownika.

---
**Kroki do odtworzenia błędu:**
1. **Krok 1:** Uruchom aplikację i zacznij proces wypiekania ciasteczek.  
2. **Krok 2:** Otwórz menu i wybierz opcję **"Back to Baking"**.  
3. **Krok 3:** Zaobserwuj, że proces wypiekania ciasteczek nie zostaje wznowiony, mimo wyświetlenia komunikatu **"Returning to baking…"**.
---
**Oczekiwany rezultat:**  
Po wybraniu opcji **"Back to Baking"**, użytkownik powinien zostać przekierowany z powrotem do procesu wypiekania ciasteczek.
**Rzeczywisty rezultat:**  
Program nie wraca do procesu wypiekania ciasteczek. Zamiast tego użytkownik pozostaje w obecnym stanie, co wynika z użycia komendy `break` w kodzie.

---
**Środowisko:**
- **Urządzenie:** PC  
- **System operacyjny:** Windows  
- **Przeglądarka:** Chrome 119 
---
**Dodatkowe informacje:**  
Możliwe rozwiązanie to zastąpienie komendy `break` odpowiednią logiką, która faktycznie pozwoli użytkownikowi wrócić do procesu wypiekania ciasteczek.

**Comment by NAME4YOU** [comment]
Dziękuję za zgłoszenie.

Pragnę jednak zwrócić uwagę, że zgłoszony problem wynika z niewłaściwego zrozumienia działania aplikacji oraz braku zapoznania się z dokumentacją, która jasno opisuje, że proces pieczenia ciasteczek odbywa się nieprzerwanie w tle. Oznacza to, że opcja "Back to Baking" nie ma funkcji wznowienia procesu pieczenia, ponieważ ten nigdy nie zostaje wstrzymany.

Twoje zgłoszenie sugeruje, że problem leży w logice kodu, jednak analiza wskazuje, że jest to błędne założenie. W rzeczywistości zgłoszenie dotyczy jedynie niespójności w komunikacie tekstowym, który rzeczywiście może wprowadzać w błąd użytkownika. Komunikat "Returning to baking…" może sugerować, że proces pieczenia został przerwany, co nie jest zgodne z faktycznym działaniem aplikacji.

Proszę o bardziej skrupulatne zapoznanie się z dokumentacją programu przed zgłaszaniem problemów, aby uniknąć niepotrzebnego zamieszania i błędnych wniosków w przyszłości. Dokumentacja została przygotowana właśnie po to, aby wyjaśnić działanie programu i ułatwić jego analizę.

Dziękuję za zrozumienie i liczę na bardziej precyzyjne podejście do zgłaszania potencjalnych błędów w przyszłości.

Pozdrawiam,
NAME4YOU
